core/urls.py
from django.urls import include, path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    delete_review,
    edit_review,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    CategoryView,
    order_list_view,
    search,
    page_not_found
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('review/delete/<int:pk>/', delete_review, name='delete-review'),
    path('review/edit/<int:pk>/', edit_review, name='edit-review'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('newsletter/', include('newsletter.urls')),
    path('orders/', order_list_view, name='order-list'),
    path('search/', search, name='search'),
    path('page-not-found/', page_not_found , name='page_not_found'),
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from contact import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('newsletter/', include('newsletter.urls')),
    path('', include('contact.urls')),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

]


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                            document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)'''

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% include "header.html" %}

  {% block head_title %}{% endblock %}
  {% block extra_head %} {% endblock %}
<body>
  

  {% comment %} <div class="animsition"></div> {% endcomment %}
    {% include "nav.html"%}
    
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}

        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>

    {% endfor %} 
    {% endif %} 

    {% block content %} 
    {% endblock content %}

     {% block extra_body %} 
     {% endblock %} 

    {% include "footer.html"%} 
    {% include "script.html"%}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
  
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  </body>
</html>

templates/delete_review.html
<!-- templates/delete_review.html -->
{% extends 'base.html' %}

{% block content %}
    <h2>Delete Review</h2>
    <p>Are you sure you want to delete this review?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
    <a href="{% url 'product' review.item.slug %}">Cancel</a>
{% endblock %}

templates/edit_review.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="padding-bottom: 10%;">
    <h2>Edit Review</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group star-rating">
            <div>
                <i class="fa fa-star" data-rating="1"></i>
                <i class="fa fa-star" data-rating="2"></i>
                <i class="fa fa-star" data-rating="3"></i>
                <i class="fa fa-star" data-rating="4"></i>
                <i class="fa fa-star" data-rating="5"></i>
            </div>
            {{ form.rating }}
        </div>
        <div class="form-group">
            {{ form.comment.label_tag }}
            {{ form.comment }}
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const stars = document.querySelectorAll('.star-rating .fa-star');
        const ratingInput = document.querySelector('input[name="rating"]');
        
        // Set the initial rating from the form
        const initialRating = ratingInput.value;
        stars.forEach(star => {
            if (star.getAttribute('data-rating') <= initialRating) {
                star.classList.add('checked');
            }
        });

        stars.forEach(star => {
            star.addEventListener('click', function () {
                const rating = this.getAttribute('data-rating');
                ratingInput.value = rating;
                stars.forEach(s => {
                    if (s.getAttribute('data-rating') <= rating) {
                        s.classList.add('checked');
                    } else {
                        s.classList.remove('checked');
                    }
                });
            });
        });
    });
</script>
{% endblock %}

templates/item_list.html
{% extends "base.html" %} {% block content %}

<h2>Here is the list of items</h2>

{% endblock content%}

templates/nav.html
{% load cart_template_tags %}
{% load category_template_tags %}
<header>
	<div class="text-dark p-2" style="background-color: rgb(173, 20, 243);">
		<div class="container d-flex flex-column flex-md-row justify-content-between align-items-center">
		<div class="mb-3 mb-md-0">
			<a href="https://web.facebook.com/" target="_blank" class="topbar-social-item fab fa-facebook me-3"></a>
			<a href="https://www.instagram.com/" target="_blank" class="topbar-social-item fab fa-instagram me-3"></a>
			<a href="https://x.com/" target="_blank" class="topbar-social-item fab fa-twitter me-3"></a>
			<a href="https://www.youtube.com/" target="_blank" class="topbar-social-item fab fa-youtube"></a>
		</div>
	
		<span class="text-center text-md-left" style="color: white; font-weight: bold;">
			Free shipping for standard order over $1599.99
		</span>
	</div>
	</div>
	
	<nav class="navbar navbar-expand-lg bg-light pt-3 pb-3 sticky-top ps-2 pe-2" >
		<div class="container">
			<a class="navbar-brand" style="font-weight: bold;" href="/">Tech Giants</a>
			<div class="d-flex align-items-center ">
				<!-- Shopping Cart Icon - visible on lg and above -->
				<div class="t-ex_re">
					
					{% if request.user.is_authenticated %}
					<li class="nav-item pe-1">
						<a class="btn btn-dark" href="/accounts/logout/" style="font-size:xx-small;">Logout</a>
						
					</li>
					{% else %}
					<div class="dropdown">
						<a class="nav-link pb-1" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
								<path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
								<path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
							  </svg>
						</a>
						<ul class="dropdown-menu" style="left: -100px;">
							<li><a class="dropdown-item" href="/accounts/login/">Login</a></li>
							<li><a class="dropdown-item" href="/accounts/signup/">SignUp</a></li>
						</ul>
					</div>
					{% endif %}
				</div>
				<div class="t-ex_re " style="padding-bottom: 5px;">
					{% if request.user.is_authenticated %}
					<a href="{% url 'core:order-summary' %}" class="position-relative text-dark ms-2 me-2 mb-4">
						<i class="fa fa-shopping-cart"></i>
						<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
							{{ request.user|cart_item_count }}
							<span class="visually-hidden">unread messages</span>
						</span>
					</a>
					{% else %}
					<a href="#" class="icon-link text-dark ms-2 me-2 mb-4" >
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-bag-fill" viewBox="0 0 16 16">
							<path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4z"/>
						  </svg>
					</a>
					{% endif %}
				</div>
				
				<!-- Navbar Toggler for smaller screens -->
				<button class="navbar-toggler border p-0" type="button" data-bs-toggle="collapse"
					style="width: 40px; height: 40px;" data-bs-target="#navbarSupportedContent"
					aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="black" class="bi bi-list"
						viewBox="0 0 16 16">
						<path fill-rule="evenodd"
							d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5" />
					</svg>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav m-auto mb-2 mb-lg-0 tech-res">
					<li class="nav-item pe-3 ps-3">
						<a class="nav-link active" aria-current="page" href="/">Home</a>
					</li>
					<li class="nav-item pe-3 ps-3">
						<a class="nav-link active" href="/shop/">Shop</a>
					</li>
					<li class="nav-item pe-3 ps-3 dropdown">
						<a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
							aria-expanded="false">
							Categories
						</a>
						<ul class="dropdown-menu ">
							<li><a class="dropdown-item" href="/category/phone/">Phones</a></li>
							<li><a class="dropdown-item" href="/category/laptop/">Laptops</a></li>

						</ul>
					</li>
					<li class="nav-item pe-3 ps-3">
						<a class="nav-link active" href="/contact/">Contact</a>
					</li>
					{% if request.user.is_authenticated %}
					<li class="nav-item pe-3 ps-3">
						<a class="nav-link active" href="/orders/">orders</a>
					</li>
					{% endif %}

				</ul>
				<div class="d-lg-flex align-items-center d-none"> <!-- Hide for screens smaller than 992px -->
					<div class="dropdown">
						<a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							<i class="fa fa-search"></i>
						</a>
						<div class="dropdown-menu dropdown-menu-end p-3 shadow-sm" style="width: 300px; border-radius: 8px;">
							<form method="GET" action="{% url 'core:search' %}">
								<div class="mb-3">
									<input type="text" class="form-control form-control-sm pt-3 pb-3" name="q"
										placeholder="Search for products..." aria-label="Search" style="border-radius: 20px;">
								</div>
								<button class="btn btn-dark w-100" type="submit" style="border-radius: 20px;">Search</button>
							</form>
						</div>
					</div>
				
					<a href="#" class="icon-link mr-3 text-dark ms-3 me-3">
						<i class="fa fa-heart"></i>
					</a>
				
					{% if request.user.is_authenticated %}
					<a href="{% url 'core:order-summary' %}" class="position-relative mr-3 text-dark ms-3 me-3">
						<i class="fa fa-shopping-cart"></i>
						<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
							{{ request.user|cart_item_count }}
							<span class="visually-hidden">unread messages</span>
						</span>
					</a>
					{% else %}
					<a href="#" class="icon-link mr-3 text-dark ms-3 me-3">
						<i class="fa fa-shopping-cart"></i>
					</a>
					{% endif %}
				
					{% if request.user.is_authenticated %}
					<li class="nav-item pe-3 ps-3">
						<a class="btn btn-dark pe-4 ps-4" href="{% url 'account_logout' %}" style="font-size: x-small;">Logout</a>
					</li>
					{% else %}
					<div class="dropdown ms-4">
						<a class="btn btn-dark pe-4 ps-4"  style="font-size: x-small;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Login
						</a>
						<ul class="dropdown-menu" style="left: -100px;">
							<li><a class="dropdown-item" href="/accounts/login/">Login</a></li>
							<li><a class="dropdown-item" href="/accounts/signup/">SignUp</a></li>
						</ul>
					</div>
					{% endif %}
				</div>
				
			</div>
		</div>
	</nav>
</header>

templates/order_snippet.html
{% comment %} 
{% block css %}

.form-control {
display: block;
width: 100%;
height: calc(1.5em + .75rem + 2px);
padding: .375rem .75rem;
font-size: 1rem;
font-weight: 400;
line-height: 1.5;
color: #495057;
background-color: #fff;
background-clip: padding-box;
border: 1px solid #ced4da !important;
border-radius: .25rem;
transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
{% endblock css %} {% endcomment %}


    <div class="col-md-4 order-md-2 mb-4 mt-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{ order.get_total }}</strong>
        </li>
      </ul>
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

templates/order_summary.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mb-4">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="mb-4">Order Summary</h2>

      <div class="table-responsive-md table-responsive-sm">
        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Image</th>
              <th scope="col">Product Name</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
              <th scope="col">Item Total</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for order_item in object.items.all %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>
                <img src="{{ order_item.item.image.url }}" class="img-fluid" style="max-width: 100px;"
                  alt="product image">
              </td>
              <td >{{ order_item.item.title }}</td>
              <td>${{ order_item.item.price }}</td>
              <td class="d-flex align-items-center">
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"
                  class="btn btn-sm btn-light">
                  <i class="fas fa-minus"></i>
                </a>
                <span class="mx-2">{{ order_item.quantity }}</span>
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}" class="btn btn-sm btn-light">
                  <i class="fas fa-plus"></i>
                </a>
              </td>
              <td>
                {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                {% else %}
                ${{ order_item.get_total_item_price }}
                {% endif %}
              </td>
              <td>
                <a href="{% url 'core:remove-from-cart' order_item.item.slug %}" class="text-danger">
                  <i class="fas fa-trash-alt"></i>
                </a>
              </td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="7" class="text-center">Your cart is empty</td>
            </tr>
            {% endfor %}
          </tbody>
          {% if object.coupon %}
          <tr>
            <td colspan="5"><b>Coupon :</b></td>
            <td colspan="2">- ${{ object.coupon.amount }}</td>
          </tr>
          {% endif %}
          {% if object.get_total %}
          <tr>
            <td colspan="5"><b>Order Total :</b></td>
            <td colspan="2"><b>${{ object.get_total }}</b></td>
          </tr>
        
          {% endif %}
        </table>
      </div>
<div class="mb-4 mt-4 flex-wrap d-flex justify-content-start align-items-center">
  <a href="/checkout" class="btn btn-warning mb-1 me-4">Checkout</a>
  <a href="/" class="btn btn-primary">Continue Shopping</a>
</div>
    </div>
  </div>
</div>


{% endblock content %}

templates/product-detail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
h4 {
	border-bottom: 2px solid #f1f1f1;
	padding-bottom: 10px;
	color: #000a38;
}

{% endblock css %}
{% block content %}

	<!-- breadcrumb -->
	<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
		<a href="/" class="s-text16">
			Home
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<a href="{% url 'core:category' object.category.slug %}" class="s-text16">
			{{ object.category }}
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<span class="s-text17">
			{{object.title}}
		</span>
	</div>

	<!-- Product Detail -->
	<div class="container bgwhite p-t-35 p-b-80">
		<div class="flex-w flex-sb">
			<div class="w-size13 p-t-30 respon5">
				<div class="wrap-slick3 flex-sb flex-w">
					<div class="wrap-slick3-dots"></div>

					<div class="slick3">
						<div class="item-slick3" data-thumb="{{ object.image.url }}">
							<div class="wrap-pic-w">
								<img src="{{ object.image.url }}" alt="{{ object.title }}">
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="w-size14 p-t-30 respon5">
				<h4 class="product-detail-name m-text16 p-b-13">
					{{object.title}}
				</h4>

				
				{% if object.discount_price %}
								<span class="block2-oldprice m-text7 p-r-5" style="font-size: 1.5rem;">
									${{ object.price }}
								</span>

								<span class="block2-newprice m-text8 p-r-5" style="font-size: 1.5rem;">
									${{ object.discount_price }}
								</span>
								{% else %}
								<span class="m-text17">
									${{object.price}}
								</span>
								{% endif %}

				<p class="s-text8 p-t-10">
					{{ object.description_short }}
				</p>

				<!--  -->
				<div class="p-t-33 p-b-60">

					<div class="flex-r-m flex-w p-t-10">
						<div class="w-size16 flex-m flex-w">
							<div class="flex-w bo5 of-hidden m-r-22 m-t-10 m-b-10">
								<button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-minus" aria-hidden="true"></i>
								</button>

								<input class="size8 m-text18 t-center num-product" type="number" name="num-product" value="1">

								<button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-plus" aria-hidden="true"></i>
								</button>
							</div>
							
							<div class="btn-addcart-product-detail size9 trans-0-4 m-t-10 m-b-10" style="margin-bottom: 20px;">
								<!-- Button -->
								
								
								
							</div>
							
							<a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary" style="margin: 2px;">Add to Cart</a>
							<a href="{{object.get_remove_from_cart_url}}" class="btn btn-outline-dark" style="margin: 2px;">Remove from Cart</a>
						</div>
					</div>
				</div>
				<br>
				<div class="p-b-45">
					<span class="s-text8 m-r-35">SKU: {{ object.stock_no }}</span>
					<span class="s-text8">Categories: {{ object.category }}</span>
				</div>
			</div>
		</div>
	</div>

	<section>
		
		<div class="container">
			<div style="margin-top: -5%;">
				<h2 style="border-bottom: 2px solid #f1f1f1;
				padding-bottom: 10px;
				color: #007BFF;">Description</h2>
				<div class="description">
					<p style="color: black;">
						{{ object.description_long|safe }}
					</p>
				</div>
			</div>

			<h2 style="margin-top: 10%;">Reviews</h2>
			<div class="reviews" style="margin: 20px 0;">
				{% for review in reviews %}
					<div class="review" style="border-bottom: 1px solid #f1f1f1; padding: 10px 0;">
						<div style="display: flex; justify-content: space-between; align-items: center;">
						<p style="color: #000000; margin: 5px 0;">
								<strong style="color: #007BFF;">{{ review.user.username }}</strong>
								{% if review.rating == 5 %}
									rated it ★★★★★
								{% elif review.rating == 4 %}
									rated it ★★★★☆
								{% elif review.rating == 3 %}
									rated it ★★★☆☆
								{% elif review.rating == 2 %}
									rated it ★★☆☆☆
								{% elif review.rating == 1 %}
									rated it ★☆☆☆☆
								{% endif %}
							</p>
			
							{% if review.user == request.user %}
								<div style="display: flex; gap: 10px;">
									<form method="post" action="{% url 'core:delete-review' review.pk %}" style="margin: 0;">
										{% csrf_token %}
										<button type="submit" class="btn btn-sm" style="background: none; border: none;" title="Delete">
											<i class="fa fa-trash"></i>
										</button>
									</form>
									<a href="{% url 'core:edit-review' review.pk %}" class="btn btn-sm" style="background: none; border: none;" title="Edit">
										<i class="fa fa-edit"></i>
									</a>
								</div>
							{% endif %}
						</div>
						
						<p style="color: #000000;">{{ review.comment }}</p>
						<p><small style="color: #999;">Posted on {{ review.created_at }}</small></p>
					</div>
				{% endfor %}
			</div>
			

			<h5>Leave a Review</h5>
			<div class="container">
				<form method="post">
					{% csrf_token %}
					<div class="form-group star-rating">
						<div>
							<i class="fa fa-star" data-rating="1"></i>
							<i class="fa fa-star" data-rating="2"></i>
							<i class="fa fa-star" data-rating="3"></i>
							<i class="fa fa-star" data-rating="4"></i>
							<i class="fa fa-star" data-rating="5"></i>
						</div>
						{{ form.rating }}
					</div>
					<div class="form-group">
						{{ form.comment.label_tag }}
						{{ form.comment }}
					</div>
					<button type="submit" class="btn btn-primary" style="margin-bottom: 5%;">Submit</button>
				</form>
			</div>


			<script>
				document.addEventListener('DOMContentLoaded', function () {
					const stars = document.querySelectorAll('.star-rating .fa-star');
					const ratingInput = document.querySelector('input[name="rating"]');
		
					stars.forEach(star => {
						star.addEventListener('click', function () {
							const rating = this.getAttribute('data-rating');
							ratingInput.value = rating;
							stars.forEach(s => {
								if (s.getAttribute('data-rating') <= rating) {
									s.classList.add('checked');
								} else {
									s.classList.remove('checked');
								}
							});
						});
					});
				});
			</script>
		</div>
	</section>
	<!-- Footer -->
	<footer class="bg6 p-t-45 p-b-43 p-l-45 p-r-45">
		<div class="flex-w p-b-90">
			<div class="w-size6 p-t-30 p-l-15 p-r-15 respon3">
				<h4 class="s-text12 p-b-30">
					GET IN TOUCH
				</h4>

				<div>
					<p class="s-text7 w-size27">
						Any questions? Let us know in store at Norrströmvägen 12B, 114 56 Stockholm, Sweden or call us on +46 8 123 4567
					</p>
				</div>
			</div>

		</div>

		<div class="t-center p-l-15 p-r-15">
			<a href="https://www.paypal.com/" target="_blank">
				<img class="h-size2" src="{% static 'images/icons/paypal.png' %}" alt="IMG-PAYPAL">
			</a>

			<a href="https://www.visa.com" target="_blank">
				<img class="h-size2" src="{% static 'images/icons/visa.png' %}" alt="IMG-VISA">
			</a>

			<a href="https://www.mastercard.us" target="_blank">
				<img class="h-size2" src="{% static 'images/icons/mastercard.png' %}" alt="IMG-MASTERCARD">
			</a>

			<a href="https://www.express.com/" target="_blank">
				<img class="h-size2" src="{% static 'images/icons/express.png' %}" alt="IMG-EXPRESS">
			</a>

			<a href="https://www.discover.com/" target="_blank">
				<img class="h-size2" src="{% static 'images/icons/discover.png' %}" alt="IMG-DISCOVER">
			</a>

			<div class="t-center s-text8 p-t-20">
				Copyright © 2024 All rights reserved.
			</div>
		</div>
	</footer>



	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="fa fa-angle-double-up" aria-hidden="true"></i>
		</span>
	</div>

	<!-- Container Selection -->
	<div id="dropDownSelect1"></div>
	<div id="dropDownSelect2"></div>

	{% endblock content %}
	